name = "basura"
main = "./src/server.ts"
compatibility_date = "2023-04-16"
route = "app.basura.gavenda.dev"
vars = { ENVIRONMENT = "production" }

[triggers]
crons = ["*/2 * * * *"]

[env.dev]
route = "dev.basura.gavenda.dev"
vars = { ENVIRONMENT = "development" }
