name = "basura"
main = "./src/server.ts"
compatibility_date = "2024-09-23"

[observability]
enabled = true

[env.prod]
route = "app.basura.gavenda.dev"
vars = { ENVIRONMENT = "production" }
d1_databases = [
  { binding = "D1", database_name = "bazura", database_id = "ebefa075-89a3-41bd-b3cc-5ae3851674c5" },
]

[env.dev]
route = "dev.basura.gavenda.dev"
vars = { ENVIRONMENT = "development" }
d1_databases = [
  { binding = "D1", database_name = "bazura", database_id = "ebefa075-89a3-41bd-b3cc-5ae3851674c5" },
]
